
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    galera_cluster_home: "clusters/{{ galera_cluster_name }}"

  tasks:

  - set_fact: galera_cluster_backup_incremental_interval="15m"
    when: galera_cluster_backup_incremental_interval is undefined

  - name: Determine cluster_pkg_folder
    set_fact:
      cluster_pkg_folder: "{{ inventory_dir | replace(playbook_dir + '/clusters/', '') }}"
    when: cluster_pkg_folder is undefined
    run_once: true

  - debug: var=cluster_pkg_folder
    run_once: true

  - set_fact: galera_cluster_home="clusters/{{ cluster_pkg_folder }}"
    
  - name: Ensure the cluster folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }} ]; then mkdir {{ galera_cluster_home }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Ensure the cluster 3-node sub-folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }}/3-node ]; then mkdir {{ galera_cluster_home }}/3-node; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Ensure the cluster 5-node sub-folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }}/5-node ]; then mkdir {{ galera_cluster_home }}/5-node; fi"
    become: false
    run_once: true
    ignore_errors: true
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Purge existing yaml from 3-node cluster
    local_action:
      module: shell
      _raw_params: "cd {{ galera_cluster_home }}/3-node && rm *.yml"
    become: false
    run_once: true
    ignore_errors: true

  - name: Purge existing yaml from 5-node cluster
    local_action:
      module: shell
      _raw_params: "cd {{ galera_cluster_home }}/5-node && rm *.yml"
    become: false
    run_once: true
    ignore_errors: true
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the 3-Node iSCSI based galera volumes manifest
    local_action:
      module: template
      src: templates/3-node/galera-3-volumes.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is undefined 

  - name: Generate the 3-Node vSphere based galera volumes manifest
    local_action:
      module: template
      src: templates/3-node/galera-3-vsphere-volumes.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-vsphere-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is defined 

  - name: Generate the 5-Node iSCSI based galera volumes manifest
    local_action:
      module: template
      src: templates/5-node/galera-5-volumes.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the 5-Node vSphere based galera volumes manifest
    local_action:
      module: template
      src: templates/5-node/galera-5-vsphere-volumes.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-vsphere-volumes.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is defined 

  - name: Generate the galera 3-nodes manifest
    local_action:
      module: template
      src: templates/3-node/galera-3-nodes.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-nodes.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera 5-nodes manifest
    local_action:
      module: template
      src: templates/5-node/galera-5-nodes.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-nodes.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the galera 3-nodes manifest with backup agent
    local_action:
      module: template
      src: templates/3-node/galera-3-nodes-backup.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-nodes-backup.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera 5-nodes manifest with backup agent
    local_action:
      module: template
      src: templates/5-node/galera-5-nodes-backup.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-nodes-backup.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the 3-nodes galera haproxy manifest
    local_action:
      module: template
      src: templates/3-node/galera-3-haproxy.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-haproxy.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the 5-nodes galera haproxy manifest
    local_action:
      module: template
      src: templates/5-node/galera-5-haproxy.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-haproxy.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the 3-node galera seed manifest
    local_action:
      module: template
      src: templates/galera-seed.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-seed.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the 5-node galera seed manifest
    local_action:
      module: template
      src: templates/galera-seed.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-seed.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'

  - name: Generate the 3-node galera external nodeport manifest
    local_action:
      module: template
      src: templates/galera-external-nodeport.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-external-nodeport.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is undefined 

  - name: Generate the 3-node galera external lb manifest
    local_action:
      module: template
      src: templates/galera-external-lb.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-external-lb.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is defined 

  - name: Generate the 5-node galera external nodeport manifest
    local_action:
      module: template
      src: templates/galera-external-access.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-external-access.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is undefined'

  - name: Generate the 5-node galera external lb manifest
    local_action:
      module: template
      src: templates/galera-external-lb.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-external-lb.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is defined 

  - name: Generate the 3-Node restore to seed job manifest
    local_action:
      module: template
      src: templates/galera-restore-seed-job.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-restore-seed-job.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the 5-node restore to seed job manifest
    local_action:
      module: template
      src: templates/galera-restore-seed-job.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-restore-seed-job.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'
    
  - name: Generate the 3-Node namespace manifest
    local_action:
      module: template
      src: templates/galera-namespace.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-namespace.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the 5-node namespace manifest
    local_action:
      module: template
      src: templates/galera-namespace.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-namespace.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined'
    
  - name: Generate the 3-Node purge volumes job manifest
    local_action:
      module: template
      src: templates/3-node/galera-3-purge-volumes-jobs.j2
      dest: "{{ galera_cluster_home }}/3-node/galera-3-purge-volumes-jobs.yml"
      mode: 0766
    run_once: true
    become: false
    when: galera_vsphere_storage_class is undefined 

  - name: Generate the 5-node purge volumes job manifest
    local_action:
      module: template
      src: templates/5-node/galera-5-purge-volumes-jobs.j2
      dest: "{{ galera_cluster_home }}/5-node/galera-5-purge-volumes-jobs.yml"
      mode: 0766
    run_once: true
    become: false
    when: 'galera_cluster_node4_iscsi_targetportal is defined and galera_vsphere_storage_class is undefined'

  - name: Generate the 3-Node killall
    local_action:
      module: template
      src: templates/3-node/killall3.j2
      dest: "{{ galera_cluster_home }}/3-node/killall3"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the 3-Node deploy
    local_action:
      module: template
      src: templates/3-node/deploy.j2
      dest: "{{ galera_cluster_home }}/3-node/deploy"
      mode: 0766
    run_once: true
    become: false
    